name: covid-artic-rampart
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - "python>=3"
  - "nodejs>=12"
  - pip
  - snakemake-minimal=5.8.1
  - biopython=1.74
  - minimap2=2.17
  - pip:
    - pysam
    - binlorry==1.3.0_alpha1
    - git+https://github.com/fmfi-compbio/Porechop.git@master
