
##### Configuration #####

#print("\nConfig object in Snakefile:")
#[print("\t{} - {}".format(k, v)) for k,v in config.items()]

# trim trailing slashes from paths to avoid snakemake complaining of double '/' in paths
config["path"]=config["annotated_path"].rstrip("/")
config["fastq_path"]=config["basecalled_path"].rstrip("/")

##### Target rules #####

rule all:
    input:
        path = config["path"], #if there is something new to be processed in the rampart output path, we want to execute this rule
        mutations_csv = config["path"]+"/results/mutations.json",
       # tmp = config["path"]+"/results/run" #tmp file to force re-run of count_and_compare rule every time pipeline is triggered by the button ..we should not need this 
    #shell: #remove the tmp file
    #    """
    #    rm {input.tmp}
    #    """

##### Modules #####
include: "rules/count_and_compare.smk"

